address:
  - location:
    originpath: "/origin1"
    destination: "localhost1"
    destinationpath: "/v1/destino1"
  - location:
    originpath: "/origin2"
    destination: "localhost2"
    destinationpath: "/v1/destino2"