address:
  - location:
    originpath: "/teste"
    destination: "localhost:8080"
    destinationpath: "/v1/metricas"
  - location:
    originpath: "/intervalo"
    destination: "localhost:8080"
    destinationpath: "/v1/intervalometricas/209"
